-- =========================================================
-- TO-DO LIST APP - SUPABASE SETUP
-- Run this in Supabase Dashboard -> SQL Editor
--
-- IMPORTANT:
-- This matches the requested no-login setup.
-- That means the table is intentionally writable through the
-- public browser client. Do not store sensitive/private data here.
-- =========================================================


-- 1) TABLE
create table if not exists public.todo_items (
    id bigint generated by default as identity primary key,

    name text not null
        check (char_length(name) between 1 and 240),

    color text not null
        default '#7c5cff',

    term text not null
        check (term in ('short', 'long')),

    sort_order integer not null
        default 0,

    created_at timestamptz not null
        default now(),

    updated_at timestamptz not null
        default now()
);


-- 2) UPDATED_AT HELPER
create or replace function public.set_todo_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;


drop trigger if exists set_todo_updated_at
on public.todo_items;


create trigger set_todo_updated_at
before update
on public.todo_items
for each row
execute function public.set_todo_updated_at();


-- 3) ROW LEVEL SECURITY
alter table public.todo_items
enable row level security;


-- Re-running this setup is safe.
drop policy if exists "todo_items_select"
on public.todo_items;

drop policy if exists "todo_items_insert"
on public.todo_items;

drop policy if exists "todo_items_update"
on public.todo_items;

drop policy if exists "todo_items_delete"
on public.todo_items;


-- No-login personal setup:
-- anon/authenticated clients can access all rows.
create policy "todo_items_select"
on public.todo_items
for select
to anon, authenticated
using (true);


create policy "todo_items_insert"
on public.todo_items
for insert
to anon, authenticated
with check (true);


create policy "todo_items_update"
on public.todo_items
for update
to anon, authenticated
using (true)
with check (true);


create policy "todo_items_delete"
on public.todo_items
for delete
to anon, authenticated
using (true);


-- 4) EXPLICIT DATA API GRANTS
-- New Supabase projects may not auto-grant these anymore.
grant usage on schema public
to anon, authenticated;

grant select, insert, update, delete
on table public.todo_items
to anon, authenticated;

grant usage, select
on sequence public.todo_items_id_seq
to anon, authenticated;


-- 5) REALTIME
-- Adds the table to the Supabase realtime publication if needed.
do $$
begin
    if not exists (
        select 1
        from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = 'todo_items'
    ) then
        alter publication supabase_realtime
        add table public.todo_items;
    end if;
end
$$;


-- 6) OPTIONAL QUICK TEST
-- Uncomment after setup if you want to confirm the table works.
--
-- insert into public.todo_items (name, color, term, sort_order)
-- values ('Supabase is working', '#7c5cff', 'short', 0);
--
-- select * from public.todo_items order by sort_order, id;
